/*
 (C) Copyright 2015, TP-Link Inc, konstantin.mauch@tp-link.com

 This program is free software; you can redistribute it and/or
 modify it under the terms of the GNU General Public License as
 published by the Free Software Foundation; either version 2 of
 the License, or (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT any WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 MA 02111-1307 USA
*/

#include <stdio.h>

#include <sys/stat.h>

/* TODO: should come as command line argument */
#define FNAME "cast.5428E.txt.voc"

int main()
{             
FILE *fp;

unsigned long ulo;

struct stat fileStats;

	/* Check if file exists, exit if does not */
	if (stat(FNAME, &fileStats) != 0)
	{

		/* Put ANSI C comment into STDOUT, so user can get some info */
		printf("/* Can't stat file %s*/ \n", FNAME);

		/* (-2) kind of failure */
		return -2;
	}
	else
	{
		/* Check if file is openable for reading, and... */
		fp=fopen(FNAME,"r");

		/* exit of not */
		if(NULL == fp)
		{
			printf("/* Some problem on FIRST opening the file %s*/ ", FNAME );

			/* (-1) another kind of failure */
			return -1;
		} 
		/* generate first part of ANSI C code - decalre variables */
		else
		{ 
		/* enumerator to provide better readability in ANSI C comments */
		int i=0;
		/* buffer to read data to */
		char c[512];


			/* ANSI C comment for better readability of autogenerated code */
			printf("/* This is AUTOGENERATED file. Do NOT edit it. */\n");

			/* include <MAX_STR_SIZE> value  */
			printf("\n#include \"constants.h\"\n");

			/* include <struct _QuineType> type  */
			printf("\n#include \"auxiliary.h\"\n\n");

			while ( !feof(fp) )
			{
				i++;

				/* Read keyword from vocabulary <cast.5428E.txt.voc> */
				fscanf(fp, "%s\n", &c[0]);

				/* ANSI C comment for better readability of autogenerated code */
				printf("/* variable for %d%s keyword found in <%s> file */\n", i, (i==1)?"st":((i==2)?"nd":((i==3)?"rd":"th")), FNAME );

				/* Declare variable (data buffer) named with keyword's name */
				printf("char %s [MAX_STR_SIZE];\n\n", &c[0]);
			}
#if (0)
			/* close file, and get prepared for second opening */
			fclose(fp);

			fp=fopen(FNAME,"r");

			if(NULL == fp)
			{
				printf("/* Some problem on SECOND opening the file %s*/ ", FNAME );

				return -1;
			} 
			else
#else
			/* Small optimization for speed, but now we're unaware of operation status. TODO: chose what is preferred: speed or stability? */
			rewind(fp);
#endif /* (0) */
			/* Generate second part of ANSI C code - put variable' names and their addresses into structure QuineArray[] */
			{ 
			/* buffer to read data to */
			char d[512];

				/* ANSI C comment for better readability of autogenerated code */
				printf("/* This array provides correspondency between name of variable name and its address */ \n");

				/* ANSI C declaration and caption of array */
				printf("struct _QuineType QuineArray[] =\n{\n");

				while ( !feof(fp) )
				{
					fscanf(fp, "%s\n", &d[0]);

					/* ANSI C declaration each array enry - first name, then address of each variable autogenerated in first part  */
					printf("\t{ &%s   , \"%s\" },\n\n", &d[0], &d[0]);
				}

				fclose(fp);

				/* Prinf ending of array, and final comment */
				printf("\t/* End of array */\n\t{0, 0}\n};\n/* End of AUTOGENERATed file */");
			}	
		}
	}

	/* int(0) is success for this primitive */
	return 0;
}
