/* This is AUTOGENERATED file. Do NOT edit it. */

#include "constants.h"
/* Decl. of variable for 1st keyword found in <cast.5428E.txt.voc> file */
char _tid_ [MAX_STR_SIZE];

/* Decl. of variable for 2nd keyword found in <cast.5428E.txt.voc> file */
char ip_address [MAX_STR_SIZE];

/* Decl. of variable for 3rd keyword found in <cast.5428E.txt.voc> file */
char ip_mask [MAX_STR_SIZE];

/* Decl. of variable for 4th keyword found in <cast.5428E.txt.voc> file */
char txt_comname [MAX_STR_SIZE];

/* Decl. of variable for 5th keyword found in <cast.5428E.txt.voc> file */
char aclId [MAX_STR_SIZE];

/* End of AUTOGENERATed file */