/* This is AUTOGENERATED file. Do NOT edit it. */

#include "constants.h"

#include "auxiliary.h"

/* variable for 1st keyword found in <cast.5428E.txt.voc> file */
char _tid_ [MAX_STR_SIZE];

/* variable for 2nd keyword found in <cast.5428E.txt.voc> file */
char ip_address [MAX_STR_SIZE];

/* variable for 3rd keyword found in <cast.5428E.txt.voc> file */
char ip_mask [MAX_STR_SIZE];

/* variable for 4th keyword found in <cast.5428E.txt.voc> file */
char txt_comname [MAX_STR_SIZE];

/* variable for 5th keyword found in <cast.5428E.txt.voc> file */
char aclId [MAX_STR_SIZE];

/* This array provides correspondency between name of variable name and its address */ 
struct _QuineType QuineArray[] =
{
	{ &_tid_   , "_tid_" },

	{ &ip_address   , "ip_address" },

	{ &ip_mask   , "ip_mask" },

	{ &txt_comname   , "txt_comname" },

	{ &aclId   , "aclId" },

	/* End of array */
	{0, 0}
};
/* End of AUTOGENERATed file */